service: cart-service

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  patterns:
    - '!node_modules/**'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

environment:
  DB_HOST: ${env:DB_HOST}
  DB_PORT: ${env:DB_PORT}
  DB_NAME: ${env:DB_NAME}
  DB_USERNAME: ${env:DB_USERNAME}
  DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  main:
    handler: dist/src/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true